#ifndef AsrItemH
#define AsrItemH

#define MIC_VOL 0x49
#define SPEAKER_VOL 0x05

#define ITEM_COUNT 8

#define STR_00 "bei jing"
#define STR_01 "shang hai"
#define STR_02 "tian jin"
#define STR_03 "chong qing"
#define STR_04 "guang zhou"
#define STR_05 "hang zhou"
#define STR_06 "cheng du"
#define STR_07 "nan jing"
#define STR_08 ""
#define STR_09 ""
#define STR_10 ""
#define STR_11 ""
#define STR_12 ""
#define STR_13 ""
#define STR_14 ""
#define STR_15 ""
#define STR_16 ""
#define STR_17 ""
#define STR_18 ""
#define STR_19 ""
#define STR_20 ""
#define STR_21 ""
#define STR_22 ""
#define STR_23 ""
#define STR_24 ""
#define STR_25 ""
#define STR_26 ""
#define STR_27 ""
#define STR_28 ""
#define STR_29 ""
#define STR_30 ""
#define STR_31 ""
#define STR_32 ""
#define STR_33 ""
#define STR_34 ""
#define STR_35 ""
#define STR_36 ""
#define STR_37 ""
#define STR_38 ""
#define STR_39 ""
#define STR_40 ""
#define STR_41 ""
#define STR_42 ""
#define STR_43 ""
#define STR_44 ""
#define STR_45 ""
#define STR_46 ""
#define STR_47 ""
#define STR_48 ""
#define STR_49 ""

#endif
